# Learn to Use the Swarmauri Package

This notebook will guide you through the process of using various components from the Swarmauri package. We will explore Local Language Models (LLMs) with Cohere, conversations, tools, toolkits, and agents. Let's get started!

## 1. Setting Up the CohereToolModel

First, we need to set up and configure our Local Language Model (LLM) using the `CohereToolModel` from the Swarmauri package. Ensure you have your API key ready and available as an environment variable named `COHERE_API_KEY`.

In [1]:
from dotenv import load_dotenv

import os
from swarmauri.standard.llms.concrete.CohereToolModel import CohereToolModel as LLM

load_dotenv()
# Retrieve the API key from environment variables
API_KEY = os.getenv('COHERE_API_KEY')

# Initialize the Cohere LLM
llm = LLM(api_key=API_KEY)
print('LLM Resource:', llm.resource)
print('LLM Type:', llm.type)

LLM Resource: LLM
LLM Type: CohereToolModel


The `resource` attribute should be `LLM`, and the `type` should be `CohereToolModel`.

### 1.1 LLM Attributes

Let's also verify the default name of the model.

In [2]:
# Check the default name of the model
print('Default Model Name:', llm.name)

Default Model Name: command-r


To see the allowed models for the CohereToolModel use the `llm.allowed_models` attribute.

In [3]:
# Check the default name of the model
print('Allowed Models:', llm.allowed_models)

Allowed Models: ['command-r', 'command-r-plus']


### 1.2 Serialization

Serialization allows converting the model data into a JSON format and back, ensuring consistency and the ability to easily store or transfer the model data.

In [4]:
# Check serialization and deserialization of the model
serialized_model_json = llm.model_dump_json()

The JSON data string can then be used to reload the LLM component.

In [5]:
deserialized_model = LLM.model_validate_json(serialized_model_json)

print('Component ID:', deserialized_model.id)

Component ID: bae069c5-b18e-4f66-8d07-d64b4f5eb8cf


## 2. Using Tools and Agents

Next, let's explore how to use tools and agents within the Swarmauri package. We will use an `AdditionTool` to perform arithmetic operations and integrate it into a toolkit.

In [6]:
from swarmauri.standard.conversations.concrete.Conversation import Conversation
from swarmauri.standard.tools.concrete.AdditionTool import AdditionTool
from swarmauri.standard.toolkits.concrete.Toolkit import Toolkit
from swarmauri.standard.agents.concrete.ToolAgent import ToolAgent

# Initialize components
conversation = Conversation()
toolkit = Toolkit()
tool = AdditionTool()

# Add the tool to the toolkit
toolkit.add_tool(tool)

# Initialize the agent
agent = ToolAgent(llm=llm, conversation=conversation, toolkit=toolkit)

# Execute a simple addition task
result = agent.exec('Add 512+671')
print('Addition Result:', result)

Addition Result: 512 + 671 = **1183**.


Here, the `ToolAgent` uses the `AdditionTool` within the `Toolkit` to compute the sum of 512 and 671. The result should be returned as a string.

## Conclusion

This notebook has demonstrated how to set up and use components from the Swarmauri package. We covered initialization of the CohereToolModel, serialization, and usage of tools and agents. Feel free to explore more tools and capabilities provided by Swarmauri to enhance your applications!