# Using the Swarmauri Package Components

This notebook demonstrates how to use various components of the Swarmauri package, including the `MistralToolModel`, `Conversation`, `AdditionTool`, `Toolkit`, and `ToolAgent` classes. These examples will guide you through the setup and utilization of these components for common tasks.

## Setup

Before using the components, make sure to have the necessary API keys set up as environment variables. In this notebook, we'll use the `MISTRAL_API_KEY` for initializing the `MistralToolModel`.

In [1]:
from dotenv import load_dotenv

import os
from swarmauri.standard.llms.concrete.MistralToolModel import MistralToolModel as LLM
from swarmauri.standard.conversations.concrete.Conversation import Conversation
from swarmauri.standard.tools.concrete.AdditionTool import AdditionTool
from swarmauri.standard.toolkits.concrete.Toolkit import Toolkit
from swarmauri.standard.agents.concrete.ToolAgent import ToolAgent

load_dotenv()

# Set up the API key
API_KEY = os.getenv('MISTRAL_API_KEY')

# Initialize the MistralToolModel
llm = LLM(api_key=API_KEY)
llm.dict(exclude='api_key')

{'name': 'open-mixtral-8x22b',
 'id': 'daea3b48-4529-4169-9d1a-5be62ee4a734',
 'members': [],
 'owner': None,
 'host': None,
 'resource': 'LLM',
 'version': '0.1.0',
 'type': 'MistralToolModel',
 'allowed_models': ['open-mixtral-8x22b',
  'mistral-small-latest',
  'mistral-large-latest']}

## Checking the LLM Resource and Type

The `MistralToolModel` is a component that interacts with the underlying language model. It has several attributes that you can access to understand its configuration.

In [2]:
# Check the resource type
print('Resource:', llm.resource)
print('Type:', llm.type)

Resource: LLM
Type: MistralToolModel


## Model Serialization and Validation

The `MistralToolModel` can be serialized to JSON and deserialized back, ensuring that the model's state can be saved and later restored or validated.

In [3]:
# Serialize and validate the model
serialized_model = llm.model_dump_json(exclude='api_key')
serialized_model

'{"name":"open-mixtral-8x22b","id":"daea3b48-4529-4169-9d1a-5be62ee4a734","members":[],"owner":null,"host":null,"resource":"LLM","version":"0.1.0","type":"MistralToolModel","allowed_models":["open-mixtral-8x22b","mistral-small-latest","mistral-large-latest"]}'

Here we deserialize the JSON, using the JSON to reload the model.

In [4]:
validated_model = LLM.model_validate_json(llm.model_dump_json())
validated_model.id == llm.id

True

## Default Model Name

The `MistralToolModel` has a default name which can be useful to identify the specific model being used.

In [5]:
# Check the default model name
print('Model Name:', llm.name)

Model Name: open-mixtral-8x22b


## Allowed Model Names

The `MistralToolModel` has a default name which can be useful to identify the specific model being used.

In [6]:
print('Allowed Models:', llm.allowed_models)

Allowed Models: ['open-mixtral-8x22b', 'mistral-small-latest', 'mistral-large-latest']


## Using the ToolAgent to Perform Tasks

The `ToolAgent` is a component that combines an LLM, a conversation context, and a toolkit to perform specific tasks. Here, we demonstrate how to set up a `ToolAgent` to perform a simple addition using the `AdditionTool`.

In [7]:
# Initialize the conversation, toolkit, and tool
conversation = Conversation()
toolkit = Toolkit()
addition_tool = AdditionTool()
toolkit.add_tool(addition_tool)

# Initialize the ToolAgent
agent = ToolAgent(llm=llm, conversation=conversation, toolkit=toolkit)

# Execute a command using the ToolAgent
result = agent.exec('Add 512+671')
print('Result:', result)

Result: The result of adding 512 and 671 is 1183.


The `ToolAgent` interprets the command and uses the appropriate tool from the toolkit to perform the task. In this case, it successfully adds the numbers 512 and 671.

## Conclusion

This notebook has demonstrated how to initialize and use various components of the Swarmauri package. You can explore further by integrating other tools and models, or by creating more complex agents tailored to your specific needs.